import E from"leaflet";
import"leaflet/dist/leaflet.css";
import"@fontsource/dm-sans/400.css";
import"@fontsource/dm-sans/500.css";
import"@fontsource/dm-sans/700.css";
import"@fontsource/caveat/500.css";
import"@fontsource/caveat/700.css";
import"@fontsource/vt323/400.css";
import"@fontsource/instrument-serif/400.css";
import"@fontsource/instrument-serif/400-italic.css";
import"./style.css";
import"./travel.css";
import{installTravel as nn}from"./travel-ui";
import{openStore as on,loadCards as an,saveCards as ve}from"./storage";
import{blankCard as rn,fillCard as sn,normalize as ht,cameraName as gt,dayOf as ln,timeOf as $,stampText as yt,placeKey as De}from"./photo";
import{drawWorld as cn,countryAt as wt,THEMES as kt}from"./world";
import{loadCities as Te,searchPlaces as bt,nameAt as vt}from"./atlas";
import{initViewer as dn,openViewer as pn,closeViewer as un,viewerIsOpen as fn}from"./viewer";
import{renderPoster as mn}from"./poster";
import*as p from"./cloud";
import { run } from './main-body';
run({ E, nn, on, an, ve, rn, sn, ht, gt, ln, $, yt, De, cn, wt, kt, Te, bt, vt, dn, pn, un, fn, mn, p });
